project:
  type: book

book:
  title: "Python Cheat Sheet"
  author: "Kittipos Sirivongrungson"
  date: "3/29/2022"
  chapters:
    - index.qmd
    - part: "Primitive"
      chapters:
      - basic/primitive.qmd
      - basic/number.qmd
      - basic/string.qmd
    - part: "Control Flow"
      chapters:
      - basic/cond.qmd
      - basic/loop.qmd
    - part: "Functions"
      chapters:
      - basic/function.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
    #documentclass: scrreprt



