project:
  type: book

book:
  title: "Python Notes"
  author: "Kittipos Sirivongrungson"
  date: "3/29/2022"
  repo-url: https://github.com/Lightbridge-KS/py-notes
  site-url: https://py-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: "Primitive"
      chapters:
      - basic/primitive.qmd
      - basic/number.qmd
      - basic/string.qmd
      - basic/data-str.qmd
    - part: "Control Flow"
      chapters:
      - basic/cond.qmd
      - basic/loop.qmd
    - part: "Functions"
      chapters:
      - basic/function.qmd
      - basic/function-02.qmd
    - part: "Error & Exception"
      chapters:
      - basic/exception.qmd
    - part: "OOP"
      chapters:
      - basic/oop.qmd
    - part: "Module & PKG"
      chapters: 
      - basic/file.qmd
      - basic/pkg.qmd
    - part: "Exercises"
      chapters:
      - basic/ctr-flow-ex.qmd
    - part: "Pandas"
      chapters: 
        - ds/pd-intro.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme:
      light: zephyr
      dark: solar
  #pdf:
    #documentclass: scrreprt

freeze: auto

