project:
  type: book

book:
  title: "Python Notes"
  author: "Kittipos Sirivongrungson"
  date: "3/29/2022"
  repo-url: https://github.com/Lightbridge-KS/py-notes
  site-url: https://py-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: "LLM Prompt"
      chapters: 
      - "contents/pref/py-pref.qmd"
    - part: "Primitive"
      chapters:
      - contents/basic/primitive.qmd
      - contents/basic/number.qmd
      - contents/basic/string.qmd
      - contents/basic/data-str.qmd
    - part: "Control Flow"
      chapters:
      - "contents/basic/cond.qmd"
      - "contents/basic/match-case.qmd"
      - "contents/basic/loop.qmd"
      - "contents/basic/comprehen.qmd"
      - "contents/basic/fun-prog.qmd"
    - part: "Functions"
      chapters:
      - "contents/basic/function.qmd"
      - "contents/basic/function-02.qmd"
      - "contents/basic/function-dec.qmd"
      - "contents/concept/closure-decorator.qmd"
      - "contents/basic/function-validate.qmd"
    - part: "Func Prog"
      chapters: 
      - "contents/concept/map-reduce.qmd"
    - part: "Error & Exception"
      chapters:
      - "contents/basic/exception.qmd"
      - "contents/try/try-else-na.qmd"
    - part: "Logging"
      chapters: 
      - "contents/logging/logging-basic.qmd"
      - "contents/logging/logging-file.qmd"
      - "contents/logging/logging-advanced.qmd"
    - part: "Regex"
      chapters: 
      - "contents/basic/regex.qmd"
      - "contents/basic/regex-re2.qmd"
    - part: "Iterate"
      chapters:
      - "contents/concept/iterable-iterator-generator.qmd"
    - part: "OOP"
      chapters:
      - "contents/oop/oop.qmd"
      - "contents/oop/oop-trick.qmd"
      - "contents/oop/oop-property.qmd"
      - "contents/oop/oop-abc.qmd"
      - "contents/oop/oop-class-instance-method.ipynb"
      - "contents/basic/dataclass.qmd"
      - "contents/playground/shape.ipynb"
      - "contents/playground/book-catalog.ipynb"
      - "contents/playground/fruits.ipynb"
      - "contents/playground/chess-game.ipynb"
    - part: "Data Validation"
      chapters: 
      - "contents/howto/typecheck.ipynb"
      - "contents/pkg/pydantic.ipynb"
    - part: "I/O"
      chapters: 
      - "contents/basic/file-ops.ipynb"
      - "contents/basic/os/os.qmd"
      - "contents/basic/path.qmd"
      - "contents/basic/json.qmd"
    - part: "Jinja"
      chapters: 
        - "contents/jinja/jinja-basic.ipynb"
        - "contents/jinja/jinja-syntax.qmd"
    - part: "FS"
      chapters: 
      - "contents/fs/fs.ipynb"
    - part: "Web"
      chapters: 
      - "contents/basic/request.qmd"
      - "contents/webscrape/bs4soup-basic.ipynb"
      - "contents/webscrape/bs4soup-fetch.ipynb"
    - part: "Context"
      chapters: 
      - "contents/basic/context/context.qmd"
      - "contents/basic/context/context-custom.ipynb"

    - part: "Typing"
      chapters: 
      - "contents/basic/typing.qmd"
    - part: "Benchmark"
      chapters: 
        - "contents/benchmark/time.qmd"
        - "contents/benchmark/timing-basic.qmd"
    - part: "Module & PKG"
      chapters: 
      - "contents/basic/file.qmd"
      - "contents/basic/pkg.qmd"
    - part: "PKG Dev"
      chapters: 
      - "contents/pkg-dev/pkg-export.qmd"
    - part: "Pipeline"
      chapters: 
      - "contents/pkg-dev/make-py-basic.qmd"
    - part: "Exercises"
      chapters:
      - "contents/basic/ctr-flow-ex.qmd"
      - "contents/playground/pg-sort.ipynb"
      - "contents/playground/minimax-game.qmd"
    - part: "Pandas"
      chapters: 
        - "contents/ds/pd-intro.qmd"
    - references.qmd


bibliography: references.bib

format:
  html:
    theme:
      light: zephyr
      dark: solar
    toc-depth: 4
  #pdf:
    #documentclass: scrreprt

freeze: auto

