project:
  type: book

book:
  title: "Python Notes"
  author: "Kittipos Sirivongrungson"
  date: "3/29/2022"
  repo-url: https://github.com/Lightbridge-KS/py-notes
  site-url: https://py-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: "LLM Prompt"
      chapters: 
      - "pref/py-pref.qmd"
    - part: "Primitive"
      chapters:
      - basic/primitive.qmd
      - basic/number.qmd
      - basic/string.qmd
      - basic/data-str.qmd
    - part: "Control Flow"
      chapters:
      - basic/cond.qmd
      - "basic/match-case.qmd"
      - basic/loop.qmd
      - "basic/comprehen.qmd"
      - basic/fun-prog.qmd
    - part: "Functions"
      chapters:
      - basic/function.qmd
      - basic/function-02.qmd
      - basic/function-dec.qmd
      - "basic/function-validate.qmd"
    - part: "Func Prog"
      chapters: 
      - "concept/map-reduce.qmd"
    - part: "Error & Exception"
      chapters:
      - basic/exception.qmd
      - "try/try-else-na.qmd"
    - part: "Logging"
      chapters: 
      - "logging/logging-basic.qmd"
      - "logging/logging-file.qmd"
      - "logging/logging-advanced.qmd"
    - part: "Regex"
      chapters: 
      - "basic/regex.qmd"
      - "basic/regex-re2.qmd"
    - part: "Iterate"
      chapters:
      - "concept/iterable-iterator-generator.qmd"
    - part: "OOP"
      chapters:
      - "oop/oop.qmd"
      - "oop/oop-trick.qmd"
      - "oop/oop-property.qmd"
      - "oop/oop-abc.qmd"
      - "oop/oop-class-instance-method.ipynb"
      - "basic/dataclass.qmd"
      - "playground/shape.ipynb"
      - "playground/book-catalog.ipynb"
      - "playground/fruits.ipynb"
      - "playground/chess-game.ipynb"
    - part: "Data Validation"
      chapters: 
      - "howto/typecheck.ipynb"
      - "pkg/pydantic.ipynb"
    - part: "I/O"
      chapters: 
      - "basic/file-ops.ipynb"
      - basic/os/os.qmd
      - basic/path.qmd
      - basic/json.qmd
    - part: "Jinja"
      chapters: 
        - "jinja/jinja-basic.ipynb"
        - "jinja/jinja-syntax.qmd"
    - part: "FS"
      chapters: 
      - "fs/fs.ipynb"
    - part: "Web"
      chapters: 
      - "basic/request.qmd"
    - part: "Context"
      chapters: 
      - basic/context/context.qmd
      - "basic/context/context-custom.ipynb"

    - part: "Typing"
      chapters: 
      - "basic/typing.qmd"
    - part: "Benchmark"
      chapters: 
        - "benchmark/time.qmd"
        - "benchmark/timing-basic.qmd"
    - part: "Module & PKG"
      chapters: 
      - basic/file.qmd
      - basic/pkg.qmd
    - part: "PKG Dev"
      chapters: 
      - "pkg-dev/pkg-export.qmd"
    - part: "Pipeline"
      chapters: 
      - "pkg-dev/make-py-basic.qmd"
    - part: "Exercises"
      chapters:
      - basic/ctr-flow-ex.qmd
      - "playground/pg-sort.ipynb"
      - "playground/minimax-game.qmd"
    - part: "Pandas"
      chapters: 
        - ds/pd-intro.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme:
      light: zephyr
      dark: solar
    toc-depth: 4
  #pdf:
    #documentclass: scrreprt

freeze: auto

