project:
  type: book

book:
  title: "Python Notes"
  author: "Kittipos Sirivongrungson"
  date: "3/29/2022"
  repo-url: https://github.com/Lightbridge-KS/py-notes
  site-url: https://py-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: "Primitive"
      chapters:
      - basic/primitive.qmd
      - basic/number.qmd
      - basic/string.qmd
      - basic/data-str.qmd
    - part: "Control Flow"
      chapters:
      - basic/cond.qmd
      - "basic/match-case.qmd"
      - basic/loop.qmd
      - "basic/comprehen.qmd"
      - basic/fun-prog.qmd
    - part: "Functions"
      chapters:
      - basic/function.qmd
      - basic/function-02.qmd
      - basic/function-dec.qmd
    - part: "Func Prog"
      chapters: 
      - "concept/map-reduce.qmd"
    - part: "Error & Exception"
      chapters:
      - basic/exception.qmd
    - part: "Iterate"
      chapters:
      - "concept/iterable-iterator-generator.qmd"
    - part: "OOP"
      chapters:
      - basic/oop.qmd
      - basic/oop-abc.qmd
      - "basic/oop-class-instance-method.ipynb"
      - basic/dataclass.qmd
      - "playground/shape.ipynb"
    - part: "Data Validation"
      chapters: 
      - "howto/typecheck.ipynb"
      - "pkg/pydantic.ipynb"
    - part: "I/O"
      chapters: 
      - basic/os/os.qmd
      - basic/path.qmd
      - basic/json.qmd
    - part: "Web"
      chapters: 
      - "basic/request.qmd"
    - part: "Context"
      chapters: 
      - basic/context/context.qmd
    - part: "Typing"
      chapters: 
      - "basic/typing.qmd"
    - part: "Module & PKG"
      chapters: 
      - basic/file.qmd
      - basic/pkg.qmd
    - part: "Exercises"
      chapters:
      - basic/ctr-flow-ex.qmd
      - "playground/pg-sort.ipynb"
    - part: "Pandas"
      chapters: 
        - ds/pd-intro.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme:
      light: zephyr
      dark: solar
    toc-depth: 4
  #pdf:
    #documentclass: scrreprt

freeze: auto

